[versions]
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"

jvm = "17"
agp = "8.4.0-alpha03"

compose_compiler = "1.5.8"

room = "2.6.1"
media3 = "1.2.1"
ktor = "2.3.8"
detekt = "1.23.5"
workmanager = "2.9.0"

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
android_library = { id = "com.android.library", version.ref = "agp" }
android_lint = { id = "com.android.lint", version.ref = "agp" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
core_ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }

kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.0" }
kotlin_datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.5.0" }
kotlin_immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.7" }

compose_bom = { module = "androidx.compose:compose-bom", version = "2024.02.00" }
compose_animation = { module = "androidx.compose.animation:animation" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version = "1.6.2" }
compose_ui = { module = "androidx.compose.ui:ui" }
compose_ui_util = { module = "androidx.compose.ui:ui-util" }
compose_ripple = { module = "androidx.compose.material:material-ripple" }
compose_material3 = { module = "androidx.compose.material3:material3", version = "1.2.0" }

compose_activity = { module = "androidx.activity:activity-compose", version = "1.8.2" }
compose_shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version = "1.2.0" }
compose_coil = { module = "io.coil-kt:coil-compose", version = "2.5.0" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
exoplayer_workmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "media3" }
workmanager = { module = "androidx.work:work-runtime", version.ref = "workmanager" }
workmanager_ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }

ktor_http = { module = "io.ktor:ktor-http", version.ref = "ktor" }

ktor_client_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor_client_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_content_negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_client_encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor_client_serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor_serialization_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

brotli = { module = "org.brotli:dec", version = "0.1.2" }
palette = { module = "androidx.palette:palette", version = "1.0.0" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }

detekt_compose = { module = "io.nlopez.compose.rules:detekt", version = "0.3.11" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
